language: ruby
cache: bundler
bundler_args: --without production

rvm:
 - 2.7.0
 
before_install:
 - gem install bundler:2.2.11

script:
 - bundle exec rspec
 
deploy:
 provider: heroku
 api_key: 4f885f43-7685-46cf-82d8-c53527c9ed10
 app: Cs3300
 run: "rake db:migrate"
 on:
  all_branches: true